"""create_file_link

Revision ID: 0894e85032e8
Revises: 944a6a0d9574
Create Date: 2025-09-19 21:36:44.143293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0894e85032e8'
down_revision: Union[str, Sequence[str], None] = '944a6a0d9574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_url', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'filepath')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('documents', 'description')
    op.drop_column('documents', 'file_url')
    # ### end Alembic commands ###
