"""Create crosswalks table

Revision ID: 3a2ef1f25793
Revises: 24aa6b117633
Create Date: 2025-09-20 10:02:16.375777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '3a2ef1f25793'
down_revision: Union[str, Sequence[str], None] = '24aa6b117633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crosswalks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('has_traffic_light', sa.Boolean(), nullable=True),
    sa.Column('near_educational_institution', sa.Boolean(), nullable=True),
    sa.Column('has_t7', sa.Boolean(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crosswalks_geom', 'crosswalks', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_crosswalks_id'), 'crosswalks', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crosswalks_id'), table_name='crosswalks')
    op.drop_index('idx_crosswalks_geom', table_name='crosswalks', postgresql_using='gist')
    op.drop_table('crosswalks')

    # ### end Alembic commands ###
