"""add_file_fields_to_documents

Revision ID: 944a6a0d9574
Revises: da197c330510
Create Date: 2025-09-19 21:12:12.182603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944a6a0d9574'
down_revision: Union[str, Sequence[str], None] = 'da197c330510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('upload_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'upload_date')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
