"""Initial migration

Revision ID: da197c330510
Revises: 
Create Date: 2025-09-19 12:20:49.478431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'da197c330510'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # Проверяем существование индекса перед созданием
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes('roads')
    index_names = [idx['name'] for idx in indexes]

    if 'idx_roads_geom' not in index_names:
        op.create_index('idx_roads_geom', 'roads', ['geom'], unique=False, postgresql_using='gist')

    op.create_index(op.f('ix_roads_id'), 'roads', ['id'], unique=False)
    op.create_index(op.f('ix_roads_name'), 'roads', ['name'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_roads_name'), table_name='roads')
    op.drop_index(op.f('ix_roads_id'), table_name='roads')

    # Проверяем существование индекса перед удалением
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes('roads')
    index_names = [idx['name'] for idx in indexes]

    if 'idx_roads_geom' in index_names:
        op.drop_index('idx_roads_geom', table_name='roads', postgresql_using='gist')

    op.drop_table('roads')
    # ### end Alembic commands ###